/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package danieljuarez_lab7p2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpotifyType = new javax.swing.ButtonGroup();
        SignUpTitle = new javax.swing.JLabel();
        Spotify = new javax.swing.JRadioButton();
        SpotifyArtists = new javax.swing.JRadioButton();
        Username = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        NombreArtistico = new javax.swing.JLabel();
        tf_NombreArtistico = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        tf_Password = new javax.swing.JTextField();
        Edad = new javax.swing.JLabel();
        tf_Edad = new javax.swing.JTextField();
        LogIn = new javax.swing.JButton();
        SignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SignUpTitle.setText("Spotify Sign Up");

        SpotifyType.add(Spotify);
        Spotify.setText("Spotify");

        SpotifyType.add(SpotifyArtists);
        SpotifyArtists.setText("Spotify for Artists");
        SpotifyArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpotifyArtistsActionPerformed(evt);
            }
        });

        Username.setText("Username");

        tf_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_UsernameActionPerformed(evt);
            }
        });

        NombreArtistico.setText("Nombre Artístico");

        tf_NombreArtistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreArtisticoActionPerformed(evt);
            }
        });

        Password.setText("Password");

        Edad.setText("Edad");

        tf_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_EdadActionPerformed(evt);
            }
        });

        LogIn.setText("Log In");

        SignUp.setText("Sign Up");
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SignUp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignUpTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Spotify)
                                    .addComponent(Username))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SpotifyArtists)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_Edad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(tf_Password, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_Username, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_NombreArtistico, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addComponent(Password)
                            .addComponent(Edad)
                            .addComponent(NombreArtistico))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spotify)
                    .addComponent(SpotifyArtists))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(tf_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreArtistico)
                    .addComponent(tf_NombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(tf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edad)
                    .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogIn)
                    .addComponent(SignUp))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpotifyArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpotifyArtistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpotifyArtistsActionPerformed

    private void tf_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_UsernameActionPerformed

    private void tf_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EdadActionPerformed

    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
        boolean existe = false;
        for (int i = 0; i < AllUsers.size(); i++) {
            if (tf_Username.getText().equals(AllUsers.get(i).getUsername())) {
                existe = true;
            }
        }
        if (existe) {
            JOptionPane.showMessageDialog(this, "El Usuario Ya Existe, Haga Log In.");
            tf_Username.setText("");
            tf_Password.setText("");
            tf_Edad.setText("");
            Spotify.setSelected(false);
            SpotifyArtists.setSelected(false);
        } else {
            Date Fecha;
            Fecha = new Date();
            FileWriter fw = null;
            BufferedWriter bw = null;
            try {
                File f = null;
                f = new File("./SpotifyUsers.txt");
                fw = new FileWriter(f, true); //si NO EXISTE -> Crea || sí YA EXISTE -> Agrega
                bw = new BufferedWriter(fw);
                if (Spotify.isSelected()) {
//                bw.write(tf_Username.getText() + ";" + Spotify.getName() + ";" + Fecha);
                    bw.write(tf_Username.getText() + ";" + "Regular" + ";" + Fecha);
                    Usuario user = new Cliente(tf_Username.getText(), tf_Password.getText(), Integer.parseInt(tf_Edad.getText()));
                    AllUsers.add(user);
                    JOptionPane.showMessageDialog(this, "Usuario Creado con Éxito.");
                }
                if (SpotifyArtists.isSelected()) {
                    bw.write(tf_Username.getText() + ";" + "Artista" + ";" + Fecha);
                    Usuario user = new Artista(tf_NombreArtistico.getText(), tf_Username.getText(), tf_Password.getText(), Integer.parseInt(tf_Edad.getText()));
                    AllUsers.add(user);
                    JOptionPane.showMessageDialog(this, "Artista Creado con Éxito.");
                }
                bw.newLine();
                bw.flush();
                bw.close();
                fw.close();
            } catch (Exception e) {
            }
            tf_Username.setText("");
            tf_Password.setText("");
            tf_Edad.setText("");
            Spotify.setSelected(false);
            SpotifyArtists.setSelected(false);
        }
    }//GEN-LAST:event_SignUpMouseClicked

    private void tf_NombreArtisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreArtisticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreArtisticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edad;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel NombreArtistico;
    private javax.swing.JLabel Password;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel SignUpTitle;
    private javax.swing.JRadioButton Spotify;
    private javax.swing.JRadioButton SpotifyArtists;
    private javax.swing.ButtonGroup SpotifyType;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField tf_Edad;
    private javax.swing.JTextField tf_NombreArtistico;
    private javax.swing.JTextField tf_Password;
    private javax.swing.JTextField tf_Username;
    // End of variables declaration//GEN-END:variables
    public ArrayList<Usuario> AllUsers = new ArrayList();

}
